#!/bin/bash

echo "Project Euler - Problem 29:"
echo "How many distinct terms are in the sequence generated by a^b for 2 <= a <= 100 and 2 <= b <= 100?"
echo

function findSolutions() {
    for a in $(seq 2 100); do
        for b in $(seq 2 100); do
            # Do calculation using BC and remove line breaks
            bc <<< $a^$b | tr '\n' ' '
            # Mark end of solution by placing 'n'
            echo "n"
        done
    done
}

# Add line breaks again so we can sort and count
answer=$(findSolutions | sed -e 's/n/\n/g' | sort | uniq | wc -l)

# Subtract 1 because of extra line break
echo $(($answer - 1))
